<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            font-size: 9px;
            color: #52525b;
        }

        .footer {
            width: 100%;
            display: flex;
            align-items: center;
            justify-content: space-between;
            border-top: 1px solid #d4d4d8;
            padding: 6px 32px 0;
            gap: 16px;
        }

        .generated {
            font-size: 8.5px;
            color: #71717a;
        }

        .generated strong {
            color: #27272a;
            font-weight: 600;
        }

        .internal {
            font-size: 8px;
            font-style: italic;
            color: #a1a1aa;
            text-align: right;
        }
    </style>
</head>
<body>
    <div class="footer">
        <div class="generated">
            Generated by: <strong>{{ $storeName }}</strong> &nbsp;·&nbsp; {{ $generatedAt }}
        </div>
        <div class="internal">This document is for internal use only.</div>
    </div>
</body>
</html>
