<?php

return [
    'hero_slides' => [
        [
            'image' => '/images/home/COFFEE-MACHINES.jpg',
            'alt' => 'Coffee Machines',
        ],
        [
            'image' => '/images/home/MEAT-PREP.jpg',
            'alt' => 'Meat Preparation',
        ],
        [
            'image' => '/images/home/REFRIGERATION-SOLUTIONS.jpg',
            'alt' => 'Refrigeration Solutions',
        ],
        [
            'image' => '/images/home/RATIONAL.jpg',
            'alt' => 'Rational iCombi Pro Series',
        ],
        [
            'image' => '/images/home/ADD TO YOUR TOPLINE.jpg',
            'alt' => 'Topline',
        ],
        [
            'image' => '/images/home/BAKERY-PREP.jpg',
            'alt' => 'Bakery Prep',
        ],
    ],
    "tax_rate" => 0.16,
    "shipping_fee" => 300,
    "currency_code" => 'Ksh',
    'kenyaRegions' => [
        "Nairobi" => [
            "Nairobi",
            "Westlands",
            "Kibera",
            "Lang'ata",
            "Embakasi",
            "Mathare",
            "Ruaraka",
            "Dagoretti",
            "Kasarani",
            "Starehe"
        ],
        "Mombasa" => [
            "Mombasa",
            "Nyali",
            "Likoni",
            "Kisauni",
            "Changamwe",
            "Jomvu",
            "Miritini",
            "Port Reitz",
            "Bamburi",
            "Shanzu"
        ],
        "Kisumu" => [
            "Kisumu",
            "Ahero",
            "Maseno",
            "Winam",
            "Chemelil",
            "Muhoroni",
            "Seme",
            "Koru",
            "Kondele",
            "Kang'ombe"
        ],
        "Nakuru" => [
            "Nakuru",
            "Naivasha",
            "Gilgil",
            "Molo",
            "Njoro",
            "Rongai",
            "Kuresoi",
            "Elburgon",
            "Solai",
            "Subukia"
        ],
        "Kiambu" => [
            "Thika",
            "Kiambu",
            "Ruiru",
            "Limuru",
            "Juja",
            "Kikuyu",
            "Gatundu",
            "Kabete",
            "Wangige",
            "Kangoru"
        ],
        "Machakos" => [
            "Machakos",
            "Athi River",
            "Mavoko",
            "Mwala",
            "Kangundo",
            "Yatta",
            "Matuu",
            "Kangari",
            "Katangi",
            "Kalama"
        ],
        "Meru" => [
            "Meru",
            "Maua",
            "Nkubu",
            "Imenti",
            "Buuri",
            "Tigania",
            "Kibirichia",
            "Kionyo",
            "Kibiriti",
            "Ruguru"
        ],
        "Nyeri" => [
            "Nyeri",
            "Othaya",
            "Tetu",
            "Naro Moru",
            "Karatina",
            "Mathira",
            "Kieni",
            "Mukurwe-ini",
            "Kigumo",
            "Karatina"
        ],
        "Muranga" => [
            "Maragua",
            "Murang'a",
            "Kangari",
            "Kandara",
            "Kiharu",
            "Kiumba",
            "Gatanga",
            "Kandara Town",
            "Kandara",
            "Makuyu"
        ],
        "Kakamega" => [
            "Kakamega",
            "Lurambi",
            "Shinyalu",
            "Ikolomani",
            "Mumias",
            "Butere",
            "Matungu",
            "Lugari",
            "Khwisero",
            "Bumula"
        ],
        "Bungoma" => [
            "Bungoma",
            "Bumula",
            "Mt Elgon",
            "Webuye",
            "Bumula",
            "Mumias",
            "Chwele",
            "Tongaren",
            "Kabuchai",
            "Kimilili"
        ],
        "UasinGishu" => [
            "Eldoret",
            "Timboroa",
            "Kesses",
            "Soy",
            "Kapseret",
            "Moiben",
            "Turbo",
            "Kapsowar",
            "Kipchamo",
            "Kesses Town"
        ],
        "Kisii" => [
            "Kisii",
            "Kegati",
            "Nyamira",
            "Boke",
            "Suneka",
            "Bomachoge",
            "Ogembo",
            "Maniga",
            "Kitutu",
            "Nyaribari"
        ],
        "Kericho" => [
            "Kericho",
            "Kipkelion",
            "Bureti",
            "Ainamoi",
            "Kesses",
            "Londiani",
            "Soin",
            "Kaplat",
            "Litein",
            "Kelong"
        ],
        "Laikipia" => [
            "Nanyuki",
            "Nanyuki Town",
            "Naro Moru",
            "Rumuruti",
            "Nyahururu",
            "Ol Moran",
            "Ng'arua",
            "Kinoo",
            "Mutara",
            "Kabaru"
        ],
        "Kitui" => [
            "Kitui",
            "Mwingi",
            "Mutomo",
            "Migwani",
            "Nangili",
            "Tawa",
            "Ikutha",
            "Kanziko",
            "Katse",
            "Zombe"
        ],
        "Turkana" => [
            "Lodwar",
            "Kakuma",
            "Lokichogio",
            "Kapedo",
            "Kakrini",
            "Keter",
            "Nakalale",
            "Kapua",
            "Kalokol",
            "Kachoda"
        ],
        "Garissa" => [
            "Garissa",
            "Dadaab",
            "Ijara",
            "Hulugho",
            "Bura",
            "Fafi",
            "Saka",
            "Damajale",
            "Masalani",
            "Subjecta"
        ],
        "Isiolo" => [
            "Isiolo",
            "Merti",
            "Garba Tulla",
            "Kinna",
            "Ngaremara",
            "Sericho",
            "Kinna Town",
            "Kipsing",
            "Isiolo Town",
            "Oldonyiro"
        ],
        "Kajiado" => [
            "Kajiado",
            "Ngong",
            "Kitengela",
            "Isinya",
            "Kiserian",
            "Oloosirkon",
            "Emali",
            "Namanga",
            "Kajiado Town",
            "Sultan Hamud"
        ]
    ],
    "promotionalBanners" => [
        [
            'title' => 'Save Big on Convection Ovens',
            'subtitle' => '10-Tray Capacity - Ideal for Bakeries & Restaurants',
            'image' => 'images/promotional_banners/COFFEE MACHINES.png',
            'code' => 'BAKE15',
            'badge' => 'SAVE 15%',
            'badge_color' => 'bg-orange-500',
        ],
        [
            'title' => 'Commercial Food Processors',
            'subtitle' => 'Speed Up Your Kitchen Prep - Professional Performance',
            'image' => 'images/promotional_banners/MEAT-PREP.jpg',
            'code' => 'CHOP20',
            'badge' => '20% OFF',
            'badge_color' => 'bg-red-600',
        ],
        [
            'title' => 'Wine & Beverage Coolers',
            'subtitle' => 'Perfect Storage for Restaurants, Bars & Hotels',
            'image' => 'images/promotional_banners/REFRIGERATION SOLUTIONS.png',
            'code' => 'CHILL',
            'badge' => 'TRENDING',
            'badge_color' => 'bg-purple-600',
        ],
        [
            'title' => 'Rational iCombi Pro Series',
            'subtitle' => 'World-Class Combi Ovens - Now in Stock',
            'image' => 'images/promotional_banners/1698387370_ICP61G.jpg',
            'code' => 'RATIONAL',
            'badge' => 'PREMIUM',
            'badge_color' => 'bg-amber-600',
        ],
    ]
];